In [1]:
import numpy as np
from data_prep import features, targets, features_test, targets_test

In [2]:
np.random.seed(42)

In [3]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

In [4]:
# Hyperparameters
n_hidden = 3  # number of hidden units
epochs = 500
learnrate = 0.05

In [8]:
features.head()

gre       gpa  rank_1  rank_2  rank_3  rank_4
209 -0.066657  0.289305     0.0     1.0     0.0     0.0
280  0.625884  1.445476     0.0     1.0     0.0     0.0
33   1.837832  1.603135     0.0     0.0     1.0     0.0
210  1.318426 -0.131120     0.0     0.0     0.0     1.0
93  -0.066657 -1.208461     0.0     1.0     0.0     0.0

In [9]:
n_records, n_features = features.shape
last_loss = None
n_records, n_features

(360, 6)

In [6]:
# Initialize weights
weights_input_hidden = np.random.normal(scale=1 / n_features ** .5,
                                        size=(n_features, n_hidden))
weights_hidden_output = np.random.normal(scale=1 / n_features ** .5,
                                         size=n_hidden)

In [12]:
weights_hidden_output

array([-0.37069928, -0.57657057,  0.5983486 ])

In [13]:
weights_input_hidden

array([[ 0.2027827 , -0.05644616,  0.26441774],
       [ 0.62177434, -0.09559271, -0.09558601],
       [ 0.64471093,  0.31330392, -0.19166212],
       [ 0.22149921, -0.18918948, -0.19013338],
       [ 0.09878068, -0.78109339, -0.70419476],
       [-0.22955292, -0.41348657,  0.12829094]])

In [15]:
del_w_hidden_output

array([ 0.,  0.,  0.])

In [16]:
del_w_input_hidden

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
features.values

array([[-0.06665712,  0.28930534,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 0.62588442,  1.44547565,  0.        ,  1.        ,  0.        ,
         0.        ],
       [ 1.83783211,  1.60313523,  0.        ,  0.        ,  1.        ,
         0.        ],
       ..., 
       [-0.41292789, -0.57782239,  1.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.62588442,  1.60313523,  1.        ,  0.        ,  0.        ,
         0.        ],
       [-0.41292789, -0.28877981,  1.        ,  0.        ,  0.        ,
         0.        ]])

In [14]:
for e in range(epochs):
    del_w_input_hidden = np.zeros(weights_input_hidden.shape)
    del_w_hidden_output = np.zeros(weights_hidden_output.shape)
    for x, y in zip(features.values, targets):
        ## Forward pass ##
        # TODO: Calculate the output
        hidden_input = None
        hidden_activations = None
        hidden_act_output = None
        output = None
        hidden_input = np.dot(weights_input_hidden, x)
        hidden_activations = sigmoid(hidden_input)
        output = sigmoid(weights_hidden_output * hidden_activations) 

In [ ]:
## Backward pass ##
# TODO: Calculate the error
error = None

In [ ]:
# TODO: Calculate error gradient in output unit
output_error = None

In [ ]:
# TODO: propagate errors to hidden layer
hidden_error = None

In [ ]:
# TODO: Update the change in weights
del_w_hidden_output += 0
del_w_input_hidden += 0

In [ ]:
# TODO: Update weights
weights_input_hidden += 0
weights_hidden_output += 0

In [ ]:
# Printing out the mean square error on the training set
if e % (epochs / 10) == 0:
    hidden_activations = sigmoid(np.dot(x, weights_input_hidden))
    out = sigmoid(np.dot(hidden_activations,
                         weights_hidden_output))
    loss = np.mean((out - targets) ** 2)

    if last_loss and last_loss < loss:
        print("Train loss: ", loss, "  WARNING - Loss Increasing")
    else:
        print("Train loss: ", loss)
    last_loss = loss

In [ ]:
# Calculate accuracy on test data
hidden = sigmoid(np.dot(features_test, weights_input_hidden))
out = sigmoid(np.dot(hidden, weights_hidden_output))
predictions = out > 0.5
accuracy = np.mean(predictions == targets_test)
print("Prediction accuracy: {:.3f}".format(accuracy))